/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SoilData {
    potassium: bigint;
    phosphorus: bigint;
    last_updated: Timestamp;
    fertility_score: bigint;
    location: string;
    nitrogen: bigint;
}
export interface PlaceBidPayload {
    bid_amount: bigint;
    crop_id: CropId;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type AlertId = bigint;
export type BidId = bigint;
export interface Bid {
    timestamp: Timestamp;
    bid_amount: bigint;
    crop_id: CropId;
    bidder_id: UserId;
    bid_id: BidId;
}
export interface Crop {
    status: CropStatus;
    quantity_kg: bigint;
    base_price: bigint;
    created_at: Timestamp;
    user_id: UserId;
    crop_type: string;
    crop_id: CropId;
    harvest_date: string;
}
export type CreateOrderResult = {
    __kind__: "ok";
    ok: {
        order: Order;
        checkout_url: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface Order {
    status: OrderStatus;
    quantity_kg: bigint;
    stripe_checkout_url?: string;
    seller_id: UserId;
    total_amount_paise: bigint;
    timestamp: Timestamp;
    stripe_session_id?: string;
    buyer_id: UserId;
    order_id: OrderId;
    crop_id: CropId;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UpdateSoilPayload {
    potassium: bigint;
    phosphorus: bigint;
    fertility_score: bigint;
    location: string;
    nitrogen: bigint;
}
export type UserId = Principal;
export interface CreateCropPayload {
    quantity_kg: bigint;
    base_price: bigint;
    crop_type: string;
    harvest_date: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type CropId = bigint;
export interface CreateOrderPayload {
    quantity_kg: bigint;
    success_url: string;
    seller_id: UserId;
    total_amount_paise: bigint;
    cancel_url: string;
    crop_name: string;
    crop_id: CropId;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface Alert {
    alert_type: AlertType;
    created_at: Timestamp;
    user_id: UserId;
    alert_id: AlertId;
    message: string;
    read_status: boolean;
}
export type OrderId = bigint;
export interface UserProfile {
    preferredLanguage: string;
    name: string;
    phoneNumber: string;
    location: string;
}
export enum AlertType {
    task = "task",
    weather = "weather"
}
export enum CropStatus {
    closed = "closed",
    sold = "sold",
    listed = "listed"
}
export enum OrderStatus {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export interface backendInterface {
    createCheckoutSession(payload: CreateOrderPayload): Promise<CreateOrderResult>;
    createCrop(payload: CreateCropPayload): Promise<Crop>;
    getAlerts(): Promise<Array<Alert>>;
    getBidsForCrop(crop_id: CropId): Promise<Array<Bid>>;
    getCrops(): Promise<Array<Crop>>;
    getMyOrders(): Promise<Array<Order>>;
    getOrder(order_id: OrderId): Promise<Order | null>;
    getSoilData(location: string): Promise<SoilData | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(phoneNumber: string): Promise<UserProfile | null>;
    isStripeConfigured(): Promise<boolean>;
    loginUser(phoneNumber: string, password: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markAlertRead(alert_id: AlertId): Promise<boolean>;
    placeBid(payload: PlaceBidPayload): Promise<{
        __kind__: "ok";
        ok: Bid;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(phoneNumber: string, name: string, location: string, preferredLanguage: string, password: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setStripeConfiguration(secretKey: string, allowedCountries: Array<string>): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSoilData(payload: UpdateSoilPayload): Promise<SoilData>;
    updateUserLanguage(phoneNumber: string, preferredLanguage: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Alert as _Alert, AlertId as _AlertId, AlertType as _AlertType, Bid as _Bid, CreateOrderResult as _CreateOrderResult, Crop as _Crop, CropId as _CropId, CropStatus as _CropStatus, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, SoilData as _SoilData, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCheckoutSession(arg0: CreateOrderPayload): Promise<CreateOrderResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0);
                return from_candid_CreateOrderResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0);
            return from_candid_CreateOrderResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCrop(arg0: CreateCropPayload): Promise<Crop> {
        if (this.processError) {
            try {
                const result = await this.actor.createCrop(arg0);
                return from_candid_Crop_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCrop(arg0);
            return from_candid_Crop_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBidsForCrop(arg0: CropId): Promise<Array<Bid>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBidsForCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBidsForCrop(arg0);
            return result;
        }
    }
    async getCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrops();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrops();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoilData(arg0: string): Promise<SoilData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoilData(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoilData(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAlertRead(arg0: AlertId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertRead(arg0);
            return result;
        }
    }
    async placeBid(arg0: PlaceBidPayload): Promise<{
        __kind__: "ok";
        ok: Bid;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBid(arg0);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBid(arg0);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSoilData(arg0: UpdateSoilPayload): Promise<SoilData> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSoilData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSoilData(arg0);
            return result;
        }
    }
    async updateUserLanguage(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserLanguage(arg0, arg1);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserLanguage(arg0, arg1);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AlertType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CreateOrderResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateOrderResult): CreateOrderResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_CropStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropStatus): CropStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Crop_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crop): Crop {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SoilData]): SoilData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CropStatus;
    quantity_kg: bigint;
    base_price: bigint;
    created_at: _Timestamp;
    user_id: _UserId;
    crop_type: string;
    crop_id: _CropId;
    harvest_date: string;
}): {
    status: CropStatus;
    quantity_kg: bigint;
    base_price: bigint;
    created_at: Timestamp;
    user_id: UserId;
    crop_type: string;
    crop_id: CropId;
    harvest_date: string;
} {
    return {
        status: from_candid_CropStatus_n11(_uploadFile, _downloadFile, value.status),
        quantity_kg: value.quantity_kg,
        base_price: value.base_price,
        created_at: value.created_at,
        user_id: value.user_id,
        crop_type: value.crop_type,
        crop_id: value.crop_id,
        harvest_date: value.harvest_date
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alert_type: _AlertType;
    created_at: _Timestamp;
    user_id: _UserId;
    alert_id: _AlertId;
    message: string;
    read_status: boolean;
}): {
    alert_type: AlertType;
    created_at: Timestamp;
    user_id: UserId;
    alert_id: AlertId;
    message: string;
    read_status: boolean;
} {
    return {
        alert_type: from_candid_AlertType_n16(_uploadFile, _downloadFile, value.alert_type),
        created_at: value.created_at,
        user_id: value.user_id,
        alert_id: value.alert_id,
        message: value.message,
        read_status: value.read_status
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: _Order;
    checkout_url: string;
}): {
    order: Order;
    checkout_url: string;
} {
    return {
        order: from_candid_Order_n4(_uploadFile, _downloadFile, value.order),
        checkout_url: value.checkout_url
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OrderStatus;
    quantity_kg: bigint;
    stripe_checkout_url: [] | [string];
    seller_id: _UserId;
    total_amount_paise: bigint;
    timestamp: _Timestamp;
    stripe_session_id: [] | [string];
    buyer_id: _UserId;
    order_id: _OrderId;
    crop_id: _CropId;
}): {
    status: OrderStatus;
    quantity_kg: bigint;
    stripe_checkout_url?: string;
    seller_id: UserId;
    total_amount_paise: bigint;
    timestamp: Timestamp;
    stripe_session_id?: string;
    buyer_id: UserId;
    order_id: OrderId;
    crop_id: CropId;
} {
    return {
        status: from_candid_OrderStatus_n6(_uploadFile, _downloadFile, value.status),
        quantity_kg: value.quantity_kg,
        stripe_checkout_url: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.stripe_checkout_url)),
        seller_id: value.seller_id,
        total_amount_paise: value.total_amount_paise,
        timestamp: value.timestamp,
        stripe_session_id: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.stripe_session_id)),
        buyer_id: value.buyer_id,
        order_id: value.order_id,
        crop_id: value.crop_id
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    sold: null;
} | {
    listed: null;
}): CropStatus {
    return "closed" in value ? CropStatus.closed : "sold" in value ? CropStatus.sold : "listed" in value ? CropStatus.listed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    task: null;
} | {
    weather: null;
}): AlertType {
    return "task" in value ? AlertType.task : "weather" in value ? AlertType.weather : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        order: _Order;
        checkout_url: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        order: Order;
        checkout_url: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n24(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Bid;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Bid;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : "failed" in value ? OrderStatus.failed : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Crop>): Array<Crop> {
    return value.map((x)=>from_candid_Crop_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
