/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'alert_type' : AlertType,
  'created_at' : Timestamp,
  'user_id' : UserId,
  'alert_id' : AlertId,
  'message' : string,
  'read_status' : boolean,
}
export type AlertId = bigint;
export type AlertType = { 'task' : null } |
  { 'weather' : null };
export interface Bid {
  'timestamp' : Timestamp,
  'bid_amount' : bigint,
  'crop_id' : CropId,
  'bidder_id' : UserId,
  'bid_id' : BidId,
}
export type BidId = bigint;
export interface CreateCropPayload {
  'quantity_kg' : bigint,
  'base_price' : bigint,
  'crop_type' : string,
  'harvest_date' : string,
}
export interface CreateOrderPayload {
  'quantity_kg' : bigint,
  'success_url' : string,
  'seller_id' : UserId,
  'total_amount_paise' : bigint,
  'cancel_url' : string,
  'crop_name' : string,
  'crop_id' : CropId,
}
export type CreateOrderResult = {
    'ok' : { 'order' : Order, 'checkout_url' : string }
  } |
  { 'err' : string };
export interface Crop {
  'status' : CropStatus,
  'quantity_kg' : bigint,
  'base_price' : bigint,
  'created_at' : Timestamp,
  'user_id' : UserId,
  'crop_type' : string,
  'crop_id' : CropId,
  'harvest_date' : string,
}
export type CropId = bigint;
export type CropStatus = { 'closed' : null } |
  { 'sold' : null } |
  { 'listed' : null };
export interface Order {
  'status' : OrderStatus,
  'quantity_kg' : bigint,
  'stripe_checkout_url' : [] | [string],
  'seller_id' : UserId,
  'total_amount_paise' : bigint,
  'timestamp' : Timestamp,
  'stripe_session_id' : [] | [string],
  'buyer_id' : UserId,
  'order_id' : OrderId,
  'crop_id' : CropId,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface PlaceBidPayload { 'bid_amount' : bigint, 'crop_id' : CropId }
export interface SoilData {
  'potassium' : bigint,
  'phosphorus' : bigint,
  'last_updated' : Timestamp,
  'fertility_score' : bigint,
  'location' : string,
  'nitrogen' : bigint,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateSoilPayload {
  'potassium' : bigint,
  'phosphorus' : bigint,
  'fertility_score' : bigint,
  'location' : string,
  'nitrogen' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'preferredLanguage' : string,
  'name' : string,
  'phoneNumber' : string,
  'location' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createCheckoutSession' : ActorMethod<
    [CreateOrderPayload],
    CreateOrderResult
  >,
  'createCrop' : ActorMethod<[CreateCropPayload], Crop>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getBidsForCrop' : ActorMethod<[CropId], Array<Bid>>,
  'getCrops' : ActorMethod<[], Array<Crop>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getSoilData' : ActorMethod<[string], [] | [SoilData]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'markAlertRead' : ActorMethod<[AlertId], boolean>,
  'placeBid' : ActorMethod<
    [PlaceBidPayload],
    { 'ok' : Bid } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[string, Array<string>], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSoilData' : ActorMethod<[UpdateSoilPayload], SoilData>,
  'updateUserLanguage' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];