/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const CropId = IDL.Nat;
export const CreateOrderPayload = IDL.Record({
  'quantity_kg' : IDL.Nat,
  'success_url' : IDL.Text,
  'seller_id' : UserId,
  'total_amount_paise' : IDL.Nat,
  'cancel_url' : IDL.Text,
  'crop_name' : IDL.Text,
  'crop_id' : CropId,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderId = IDL.Nat;
export const Order = IDL.Record({
  'status' : OrderStatus,
  'quantity_kg' : IDL.Nat,
  'stripe_checkout_url' : IDL.Opt(IDL.Text),
  'seller_id' : UserId,
  'total_amount_paise' : IDL.Nat,
  'timestamp' : Timestamp,
  'stripe_session_id' : IDL.Opt(IDL.Text),
  'buyer_id' : UserId,
  'order_id' : OrderId,
  'crop_id' : CropId,
});
export const CreateOrderResult = IDL.Variant({
  'ok' : IDL.Record({ 'order' : Order, 'checkout_url' : IDL.Text }),
  'err' : IDL.Text,
});
export const CreateCropPayload = IDL.Record({
  'quantity_kg' : IDL.Nat,
  'base_price' : IDL.Nat,
  'crop_type' : IDL.Text,
  'harvest_date' : IDL.Text,
});
export const CropStatus = IDL.Variant({
  'closed' : IDL.Null,
  'sold' : IDL.Null,
  'listed' : IDL.Null,
});
export const Crop = IDL.Record({
  'status' : CropStatus,
  'quantity_kg' : IDL.Nat,
  'base_price' : IDL.Nat,
  'created_at' : Timestamp,
  'user_id' : UserId,
  'crop_type' : IDL.Text,
  'crop_id' : CropId,
  'harvest_date' : IDL.Text,
});
export const AlertType = IDL.Variant({
  'task' : IDL.Null,
  'weather' : IDL.Null,
});
export const AlertId = IDL.Nat;
export const Alert = IDL.Record({
  'alert_type' : AlertType,
  'created_at' : Timestamp,
  'user_id' : UserId,
  'alert_id' : AlertId,
  'message' : IDL.Text,
  'read_status' : IDL.Bool,
});
export const BidId = IDL.Nat;
export const Bid = IDL.Record({
  'timestamp' : Timestamp,
  'bid_amount' : IDL.Nat,
  'crop_id' : CropId,
  'bidder_id' : UserId,
  'bid_id' : BidId,
});
export const SoilData = IDL.Record({
  'potassium' : IDL.Nat,
  'phosphorus' : IDL.Nat,
  'last_updated' : Timestamp,
  'fertility_score' : IDL.Nat,
  'location' : IDL.Text,
  'nitrogen' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const PlaceBidPayload = IDL.Record({
  'bid_amount' : IDL.Nat,
  'crop_id' : CropId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateSoilPayload = IDL.Record({
  'potassium' : IDL.Nat,
  'phosphorus' : IDL.Nat,
  'fertility_score' : IDL.Nat,
  'location' : IDL.Text,
  'nitrogen' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createCheckoutSession' : IDL.Func(
      [CreateOrderPayload],
      [CreateOrderResult],
      [],
    ),
  'createCrop' : IDL.Func([CreateCropPayload], [Crop], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], []),
  'getBidsForCrop' : IDL.Func([CropId], [IDL.Vec(Bid)], ['query']),
  'getCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getSoilData' : IDL.Func([IDL.Text], [IDL.Opt(SoilData)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'markAlertRead' : IDL.Func([AlertId], [IDL.Bool], []),
  'placeBid' : IDL.Func(
      [PlaceBidPayload],
      [IDL.Variant({ 'ok' : Bid, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSoilData' : IDL.Func([UpdateSoilPayload], [SoilData], []),
  'updateUserLanguage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const CropId = IDL.Nat;
  const CreateOrderPayload = IDL.Record({
    'quantity_kg' : IDL.Nat,
    'success_url' : IDL.Text,
    'seller_id' : UserId,
    'total_amount_paise' : IDL.Nat,
    'cancel_url' : IDL.Text,
    'crop_name' : IDL.Text,
    'crop_id' : CropId,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderId = IDL.Nat;
  const Order = IDL.Record({
    'status' : OrderStatus,
    'quantity_kg' : IDL.Nat,
    'stripe_checkout_url' : IDL.Opt(IDL.Text),
    'seller_id' : UserId,
    'total_amount_paise' : IDL.Nat,
    'timestamp' : Timestamp,
    'stripe_session_id' : IDL.Opt(IDL.Text),
    'buyer_id' : UserId,
    'order_id' : OrderId,
    'crop_id' : CropId,
  });
  const CreateOrderResult = IDL.Variant({
    'ok' : IDL.Record({ 'order' : Order, 'checkout_url' : IDL.Text }),
    'err' : IDL.Text,
  });
  const CreateCropPayload = IDL.Record({
    'quantity_kg' : IDL.Nat,
    'base_price' : IDL.Nat,
    'crop_type' : IDL.Text,
    'harvest_date' : IDL.Text,
  });
  const CropStatus = IDL.Variant({
    'closed' : IDL.Null,
    'sold' : IDL.Null,
    'listed' : IDL.Null,
  });
  const Crop = IDL.Record({
    'status' : CropStatus,
    'quantity_kg' : IDL.Nat,
    'base_price' : IDL.Nat,
    'created_at' : Timestamp,
    'user_id' : UserId,
    'crop_type' : IDL.Text,
    'crop_id' : CropId,
    'harvest_date' : IDL.Text,
  });
  const AlertType = IDL.Variant({ 'task' : IDL.Null, 'weather' : IDL.Null });
  const AlertId = IDL.Nat;
  const Alert = IDL.Record({
    'alert_type' : AlertType,
    'created_at' : Timestamp,
    'user_id' : UserId,
    'alert_id' : AlertId,
    'message' : IDL.Text,
    'read_status' : IDL.Bool,
  });
  const BidId = IDL.Nat;
  const Bid = IDL.Record({
    'timestamp' : Timestamp,
    'bid_amount' : IDL.Nat,
    'crop_id' : CropId,
    'bidder_id' : UserId,
    'bid_id' : BidId,
  });
  const SoilData = IDL.Record({
    'potassium' : IDL.Nat,
    'phosphorus' : IDL.Nat,
    'last_updated' : Timestamp,
    'fertility_score' : IDL.Nat,
    'location' : IDL.Text,
    'nitrogen' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const PlaceBidPayload = IDL.Record({
    'bid_amount' : IDL.Nat,
    'crop_id' : CropId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateSoilPayload = IDL.Record({
    'potassium' : IDL.Nat,
    'phosphorus' : IDL.Nat,
    'fertility_score' : IDL.Nat,
    'location' : IDL.Text,
    'nitrogen' : IDL.Nat,
  });
  
  return IDL.Service({
    'createCheckoutSession' : IDL.Func(
        [CreateOrderPayload],
        [CreateOrderResult],
        [],
      ),
    'createCrop' : IDL.Func([CreateCropPayload], [Crop], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], []),
    'getBidsForCrop' : IDL.Func([CropId], [IDL.Vec(Bid)], ['query']),
    'getCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getSoilData' : IDL.Func([IDL.Text], [IDL.Opt(SoilData)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'markAlertRead' : IDL.Func([AlertId], [IDL.Bool], []),
    'placeBid' : IDL.Func(
        [PlaceBidPayload],
        [IDL.Variant({ 'ok' : Bid, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSoilData' : IDL.Func([UpdateSoilPayload], [SoilData], []),
    'updateUserLanguage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };